export type Project = {
  id: string;
  title: string;
  slug: string;
  category: "business" | "seo" | "social" | "ai-agents";
  clientType: string;
  problem: string;
  solution: string;
  techStack: string[];
  result: string;
  featured?: boolean;
};

export const projects: Project[] = [
  {
    id: "1",
    title: "Invoice Processing Automation",
    slug: "invoice-processing-automation",
    category: "business",
    clientType: "E-commerce Business",
    problem: "Manual invoice processing was taking 10+ hours weekly, with frequent data entry errors costing hundreds in reconciliation.",
    solution: "Built an AI-powered pipeline that extracts data from PDF invoices using OCR and AI, automatically categorizes expenses, and syncs with accounting software.",
    techStack: ["n8n", "OpenAI", "Google Sheets", "QuickBooks"],
    result: "85% reduction in processing time, zero data entry errors",
    featured: true,
  },
  {
    id: "2",
    title: "LinkedIn Content Autopilot",
    slug: "linkedin-content-autopilot",
    category: "social",
    clientType: "B2B Marketing Agency",
    problem: "Client needed to post on LinkedIn 3x daily but lacked time, resulting in inconsistent presence and declining engagement.",
    solution: "Created an automated system that generates, schedules, and posts content while maintaining authentic voice and optimal posting times.",
    techStack: ["n8n", "Claude", "LinkedIn API", "Notion"],
    result: "300% increase in engagement, consistent daily posting",
    featured: true,
  },
  {
    id: "3",
    title: "AI Knowledge Base Agent",
    slug: "ai-knowledge-base-agent",
    category: "ai-agents",
    clientType: "SaaS Startup",
    problem: "Support team overwhelmed with repetitive questions, taking focus away from complex issues that need human attention.",
    solution: "Built a RAG-powered AI agent that queries internal documentation to provide instant, accurate answers to customer inquiries.",
    techStack: ["n8n", "Pinecone", "Claude", "Intercom"],
    result: "70% reduction in support tickets, 24/7 instant responses",
    featured: true,
  },
  {
    id: "4",
    title: "Auto SEO Keywords Generator",
    slug: "auto-seo-keywords-generator",
    category: "seo",
    clientType: "Digital Marketing Agency",
    problem: "Manual keyword research was time-consuming, often missing high-opportunity long-tail keywords that competitors overlooked.",
    solution: "Developed an AI engine that analyzes competitors, identifies content gaps, and generates hundreds of optimized keyword clusters.",
    techStack: ["n8n", "OpenAI", "Google Search API", "Ahrefs"],
    result: "5x faster keyword research, 40% improvement in rankings",
    featured: true,
  },
  {
    id: "5",
    title: "Customer Feedback Sentiment Analysis",
    slug: "customer-feedback-sentiment-analysis",
    category: "business",
    clientType: "Retail Brand",
    problem: "Unable to understand customer sentiment at scale - reviews and feedback went unread, missing critical product insights.",
    solution: "Built an automated pipeline that collects feedback from multiple channels, analyzes sentiment using AI, and generates actionable insights.",
    techStack: ["n8n", "OpenAI", "Slack", "Google Sheets"],
    result: "Real-time sentiment tracking, 60% faster response to issues",
    featured: true,
  },
  {
    id: "6",
    title: "Employee Onboarding System",
    slug: "employee-onboarding-system",
    category: "business",
    clientType: "Corporate Enterprise",
    problem: "Manual onboarding process took HR 10+ hours per new hire, with documents getting lost and tasks falling through cracks.",
    solution: "Created a fully automated onboarding workflow that handles document collection, account setup, training scheduling, and notifications.",
    techStack: ["n8n", "Google Workspace", "Slack", "HR Software"],
    result: "75% less HR time per hire, zero missed tasks",
    featured: true,
  },
  {
    id: "7",
    title: "Finance Tracker & Reporter",
    slug: "finance-tracker-reporter",
    category: "business",
    clientType: "Small Business",
    problem: "Financial data scattered across multiple spreadsheets, making it impossible to get real-time visibility into cash flow.",
    solution: "Built an integrated system that pulls data from bank accounts, categorizes transactions, and generates daily/weekly financial reports.",
    techStack: ["n8n", "Plaid", "Google Sheets", "Email"],
    result: "Real-time financial visibility, 5 hours saved weekly",
  },
  {
    id: "8",
    title: "Booking Support Agent",
    slug: "booking-support-agent",
    category: "business",
    clientType: "Hospitality Business",
    problem: "Missed booking inquiries during off-hours, with staff spending hours on phone confirming appointments manually.",
    solution: "Deployed an AI voice agent that handles booking inquiries, confirms appointments, and sends reminders - available 24/7.",
    techStack: ["n8n", "Vapi", "Calendar", "SMS"],
    result: "100% inquiry capture rate, 24/7 availability",
  },
  {
    id: "9",
    title: "Inbox Management Agent",
    slug: "inbox-management-agent",
    category: "business",
    clientType: "Consulting Firm",
    problem: "Email inbox overwhelmed with inquiries, important messages getting buried under promotional emails and newsletters.",
    solution: "Built an AI agent that automatically sorts, prioritizes, and drafts responses to emails based on sender and content.",
    techStack: ["n8n", "Gmail API", "Claude", "Slack"],
    result: "80% faster email processing, zero missed important emails",
  },
  {
    id: "10",
    title: "Resume AI Analyzer",
    slug: "resume-ai-analyzer",
    category: "business",
    clientType: "Recruitment Agency",
    problem: "Manual resume screening taking 20+ hours per job req, recruiters burning out on repetitive initial reviews.",
    solution: "Created an AI-powered resume screening system that scores candidates against job requirements and highlights best matches.",
    techStack: ["n8n", "OpenAI", "Google Drive", "HR Software"],
    result: "90% faster screening, improved candidate quality",
  },
  {
    id: "11",
    title: "Monthly Invoice Summarizer",
    slug: "monthly-invoice-summarizer",
    category: "business",
    clientType: "Freelancer",
    problem: "End-of-month invoice processing was chaotic, spending hours matching invoices to payments and generating reports.",
    solution: "Built an automated pipeline that matches invoices to payments, categorizes by client/project, and generates summary reports.",
    techStack: ["n8n", "QuickBooks", "Google Sheets", "Email"],
    result: "3 hours saved monthly, crystal-clear financial clarity",
  },
  {
    id: "12",
    title: "Real Estate Agent Assistant",
    slug: "real-estate-agent-assistant",
    category: "ai-agents",
    clientType: "Real Estate Agency",
    problem: "Agents spending hours on phone qualifying leads, showing properties that don't match client requirements.",
    solution: "Built an AI agent thatqualifies leads, schedules property viewings, and provides instant property recommendations.",
    techStack: ["n8n", "Claude", "CRM", "Calendar"],
    result: "5x more property showings, 60% better lead qualification",
  },
  {
    id: "13",
    title: "Business Ideas AI Agent",
    slug: "business-ideas-ai-agent",
    category: "ai-agents",
    clientType: "Entrepreneur",
    problem: "Struggling to validate business ideas, spending weeks on research that could be automated for faster decision-making.",
    solution: "Created an AI agent that researches markets, analyzes competition, and generates comprehensive business case analyses.",
    techStack: ["n8n", "OpenAI", "Web Search", "Perplexity"],
    result: "Instant business validation, data-driven decisions",
  },
  {
    id: "14",
    title: "Lead Generation via Google Maps",
    slug: "lead-generation-google-maps",
    category: "business",
    clientType: "Local Service Business",
    problem: "Manual lead discovery was time-consuming, missing local businesses that could be perfect clients.",
    solution: "Built an automated system that scrapes Google Maps for local businesses matching criteria, enriches data, and exports to CRM.",
    techStack: ["n8n", "Google Maps API", "Apollo", "HubSpot"],
    result: "500+ qualified leads per week, 80% less research time",
  },
  {
    id: "15",
    title: "Nutritionist AI Agent",
    slug: "nutritionist-ai-agent",
    category: "ai-agents",
    clientType: "Health & Wellness Practice",
    problem: "Nutritionist spending hours on initial consultations answering basic questions, limiting time for personalized diet planning.",
    solution: "Built an AI agent that handles initial consultations, gathers client history, and generates preliminary diet recommendations.",
    techStack: ["n8n", "Claude", "Google Forms", "Notion"],
    result: "50% more clients served, personalized planning time doubled",
  },
  {
    id: "16",
    title: "YouTube Videos Checker",
    slug: "youtube-videos-checker",
    category: "business",
    clientType: "Content Creator",
    problem: "Manually checking hundreds of YouTube videos daily for content inspiration, taking hours of unproductive screening.",
    solution: "Created an automated system that monitors channels, extracts key insights, and flags content opportunities based on engagement.",
    techStack: ["n8n", "YouTube API", "Slack", "Google Sheets"],
    result: "90% faster content research, never miss trends",
  },
  {
    id: "17",
    title: "Viral LinkedIn Post Generator",
    slug: "viral-linkedin-post-generator",
    category: "social",
    clientType: "Thought Leader",
    problem: "Struggling to create content that resonates, posts getting minimal engagement despite valuable insights.",
    solution: "Built an AI system that analyzes top-performing posts, generates multiple variations, and schedules optimal posting times.",
    techStack: ["n8n", "Claude", "LinkedIn API", "Notion"],
    result: "400% increase in post engagement, viral hits",
  },
  {
    id: "18",
    title: "YouTube Shorts Generator",
    slug: "youtube-shorts-generator",
    category: "social",
    clientType: "YouTuber",
    problem: "Creating short-form content was time-consuming, requiring editing skills and hours per video.",
    solution: "Automated system that generates short scripts, creates visuals, and produces ready-to-upload shorts content.",
    techStack: ["n8n", "OpenAI", "Runway", "YouTube API"],
    result: "10x content output, consistent posting schedule",
  },
  {
    id: "19",
    title: "AI Clone on Autopilot",
    slug: "ai-clone-autopilot",
    category: "social",
    clientType: "Influencer",
    problem: "Couldn't maintain consistent content presence while traveling, losing engagement and follower growth.",
    solution: "Created an AI clone that learns from past content, generates new posts in your voice, and maintains your online presence.",
    techStack: ["n8n", "ElevenLabs", "Claude", "Social APIs"],
    result: "Never miss a post, maintain authentic voice",
  },
  {
    id: "20",
    title: "Social Media Multi-Platform Connector",
    slug: "social-media-multi-platform",
    category: "social",
    clientType: "Brand",
    problem: "Managing presence across multiple platforms took full-time attention, posting same content manually everywhere.",
    solution: "Built a unified system that posts once, automatically adapts and publishes to all platforms with optimal formatting.",
    techStack: ["n8n", "Buffer", "Instagram API", "Twitter API"],
    result: "90% less social media management time",
  },
  {
    id: "21",
    title: "Image Ads Creator",
    slug: "image-ads-creator",
    category: "social",
    clientType: "E-commerce Brand",
    problem: "Creating ad creative was expensive and slow, hiring designers for every campaign variation.",
    solution: "Automated AI system that generates dozens of ad variations from product images and copy, ready for testing.",
    techStack: ["n8n", "Midjourney", "Canva API", "Facebook Ads"],
    result: "80% faster ad creative, more variations for testing",
  },
  {
    id: "22",
    title: "T-Shirt Mockup Generator",
    slug: "tshirt-mockup-generator",
    category: "social",
    clientType: "Merch Seller",
    problem: "Creating product mockups for every design took hours, slowing down product launches.",
    solution: "Automated system that instantly generates professional mockups from designs, ready for Etsy/Amazon listings.",
    techStack: ["n8n", "Midjourney", "Placeit API", "Google Drive"],
    result: "Launch products 10x faster, professional quality",
  },
  {
    id: "23",
    title: "Viral Video Generator",
    slug: "viral-video-generator",
    category: "social",
    clientType: "Content Creator",
    problem: "Viral content seemed like luck, no data-driven approach to creating content with higher viral potential.",
    solution: "AI system that analyzes trending formats, generates script variations, and produces videos optimized for virality.",
    techStack: ["n8n", "OpenAI", "CapCut", "YouTube API"],
    result: "Multiple viral videos, consistent growth",
  },
  {
    id: "24",
    title: "Stock Images Automation",
    slug: "stock-images-automation",
    category: "social",
    clientType: "Marketer",
    problem: "Searching and downloading stock images was time-consuming, often settling for less-than-ideal options.",
    solution: "Automated workflow that finds, downloads, and organizes stock images based on project requirements.",
    techStack: ["n8n", "Unsplash API", "Google Drive", "Notion"],
    result: "95% faster image sourcing",
  },
  {
    id: "25",
    title: "ASMR Video Generator",
    slug: "asmr-video-generator",
    category: "social",
    clientType: "ASMR Content Creator",
    problem: "Creating ASMR content was manually intensive, from script to editing taking days per video.",
    solution: "Automated system that generates ASMR scripts, creates audio, and produces ready-to-upload video content.",
    techStack: ["n8n", "ElevenLabs", "CapCut", "YouTube API"],
    result: "Daily content output, consistent quality",
  },
  {
    id: "26",
    title: "Seedance Viral Videos",
    slug: "seedance-viral-videos",
    category: "social",
    clientType: "Dance Creator",
    problem: "Creating dance videos required expensive equipment and editing skills, limiting content frequency.",
    solution: "AI-powered system that generates dance content with trending moves, ready for TikTok/Reels.",
    techStack: ["n8n", "Runway", "TikTok API", "CapCut"],
    result: "Viral dance content, exponential follower growth",
  },
  {
    id: "27",
    title: "YouTube Thumbnail Creator",
    slug: "youtube-thumbnail-creator",
    category: "social",
    clientType: "YouTuber",
    problem: "Thumbnails were hurting click-through rates, but design skills were limited.",
    solution: "AI system that generates click-worthy thumbnails from video titles and topics, optimized for each platform.",
    techStack: ["n8n", "DALL-E", "Canva", "YouTube API"],
    result: "45% higher CTR, professional thumbnails",
  },
  {
    id: "28",
    title: "WhatsApp AI Support Agent",
    slug: "whatsapp-ai-support",
    category: "ai-agents",
    clientType: "Business Owner",
    problem: "Missing WhatsApp messages from customers during off-hours, losing potential leads and damaging reputation.",
    solution: "AI-powered WhatsApp agent that responds instantly to inquiries, qualifies leads, and schedules callbacks.",
    techStack: ["n8n", "Twilio", "Claude", "Notion"],
    result: "100% message response rate, 24/7 availability",
  },
  {
    id: "29",
    title: "Day Trader AI Agent",
    slug: "day-trader-ai-agent",
    category: "ai-agents",
    clientType: "Day Trader",
    problem: "Manual market research taking hours each morning, often missing key opportunities.",
    solution: "AI agent that researches markets overnight, summarizes key findings, and identifies high-probability trades.",
    techStack: ["n8n", "OpenAI", "Alpha Vantage", "Slack"],
    result: "Informed trading decisions, hours saved daily",
  },
  {
    id: "30",
    title: "X/Twitter Scraper & Analyzer",
    slug: "twitter-scraper-analyzer",
    category: "ai-agents",
    clientType: "Marketing Agency",
    problem: "Manual competitor monitoring was impossible to scale, missing key market movements.",
    solution: "Automated system that scrapes competitor accounts, analyzes engagement, and alerts on important posts.",
    techStack: ["n8n", "Apify", "Claude", "Slack"],
    result: "Real-time competitor intelligence, never miss updates",
  },
  {
    id: "31",
    title: "Spotify DJ AI Agent",
    slug: "spotify-dj-ai-agent",
    category: "ai-agents",
    clientType: "Music Curator",
    problem: "Creating playlists was manual and time-consuming, never quite hitting the right mood.",
    solution: "AI agent that analyzes listening patterns, generates perfect playlists, and updates them automatically.",
    techStack: ["n8n", "Spotify API", "OpenAI", "Notion"],
    result: "Perfect playlists on autopilot, happy listeners",
  },
  {
    id: "32",
    title: "DeepSeek R1 Research Agent",
    slug: "deepseek-r1-research-agent",
    category: "ai-agents",
    clientType: "Researcher",
    problem: "Literature reviews taking weeks, manually synthesizing information from dozens of sources.",
    solution: "AI agent powered by DeepSeek R1 that researches topics, synthesizes findings, and generates comprehensive reports.",
    techStack: ["n8n", "DeepSeek", "Google Scholar", "Notion"],
    result: "10x faster research, comprehensive analysis",
  },
  {
    id: "33",
    title: "Vector Database Setup",
    slug: "vector-database-pinecone",
    category: "ai-agents",
    clientType: "Tech Startup",
    problem: "Building RAG systems required complex setup, slowing down AI application development.",
    solution: "Automated pipeline that processes documents, generates embeddings, and stores in Pinecone for instant retrieval.",
    techStack: ["n8n", "Pinecone", "OpenAI", "Google Drive"],
    result: "Instant RAG setup, faster AI development",
  },
  {
    id: "34",
    title: "Supabase Audio Agent",
    slug: "supabase-audio-agent",
    category: "ai-agents",
    clientType: "Podcast Creator",
    problem: "Transcribing and analyzing podcast episodes was manual and slow.",
    solution: "AI agent that transcribes audio, generates summaries, and extracts key quotes automatically.",
    techStack: ["n8n", "Supabase", "Whisper", "OpenAI"],
    result: "Instant transcription, shareable highlights",
  },
  {
    id: "35",
    title: "LinkedIn Main Agent",
    slug: "linkedin-main-agent",
    category: "social",
    clientType: "B2B Sales",
    problem: "LinkedIn outreach was manual and slow, not scaling despite clear opportunity.",
    solution: "Comprehensive agent that researches prospects, sends personalized connection requests, and follows up automatically.",
    techStack: ["n8n", "LinkedIn API", "Apollo", "Claude"],
    result: "10x more connections, personalized at scale",
  },
  {
    id: "36",
    title: "Long-term Memory System",
    slug: "supabase-longterm-memory",
    category: "ai-agents",
    clientType: "AI Developer",
    problem: "AI assistants couldn't remember past conversations, losing context and valuable information.",
    solution: "Built a long-term memory system using Supabase that stores conversation history for context-aware future interactions.",
    techStack: ["n8n", "Supabase", "OpenAI", "Slack"],
    result: "Context-aware AI, personalized experiences",
  },
  {
    id: "37",
    title: "Invoice Tracking System",
    slug: "invoice-tracking-system",
    category: "business",
    clientType: "Freelancer",
    problem: "Lost track of which invoices were paid, which were overdue, spending hours following up.",
    solution: "Automated tracking system that monitors payment status, sends reminders, and updates dashboards in real-time.",
    techStack: ["n8n", "Stripe", "Google Sheets", "Email"],
    result: "Zero missed payments, instant status visibility",
  },
  {
    id: "38",
    title: "AI Chatbot for Website",
    slug: "ai-chatbot-website",
    category: "ai-agents",
    clientType: "Website Owner",
    problem: "Website visitors getting no response after hours, bouncing to competitors.",
    solution: "AI-powered chatbot that engages visitors instantly, qualifies leads, and schedules consultations.",
    techStack: ["n8n", "ChatGPT", "Intercom", "Calendar"],
    result: "3x more leads captured, 24/7 engagement",
  },
];

export const categories = [
  { id: "all", name: "All", count: 38 },
  { id: "business", name: "Business Automation", count: 13 },
  { id: "seo", name: "SEO", count: 1 },
  { id: "social", name: "Social Media", count: 16 },
  { id: "ai-agents", name: "AI Agents", count: 8 },
];
